# Subtitles to be auto-selected at startup (The first one has the highest priority)
#
# Format: <langCode>-<countryCode>
# Lang list: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
# Country list: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
top_languages=tr-tr
bottom_languages=en-us,ja-jp

# Use only the matching ones, if any subtitles contain these words
preferred_words=full

# Always skip subtitles if their title contains these words
rejected_words=sign,song

# Set top subtitle as bottom subtitle if bottom subtitle is missing
use_top_as_bottom=yes

# Display secondary subtitle on hover
secondary_on_hover=no

# Secondary subtitle hover area (50 = the top half of the screen)
hover_height_percent=50

# Style settings for merged subtitles
# In MPV, styling options for secondary subtitles are quite limited. By merging subtitles, you can work around this limitation. If your video file is on an HDD, this process may take 2–3 minutes.
top_style=fn:Arial,fs:70,1c:&H0000DEFF,2c:&H000000FF,3c:&H00000000,4c:&H00000000,b:0,i:0,u:0,s:0,sx:100,sy:100,fsp:0,frz:0,bs:1,bord:3,shad:0,an:8,ml:0,mr:0,mv:40,enc:1
bottom_style=fn:Arial,fs:70,1c:&H00FFFFFF,2c:&H000000FF,3c:&H00000000,4c:&H00000000,b:0,i:0,u:0,s:0,sx:100,sy:100,fsp:0,frz:0,bs:1,bord:3,shad:0,an:2,ml:0,mr:0,mv:40,enc:1

# ASS tags for merged subtitles
# When a line is stripped based on your current settings, these tags will be added to it.
# ASS Tags Page (official): https://aegisub.org/docs/latest/ass_tags/
top_tags=
bottom_tags=\blur4

# Don’t strip sign lines
# If the ASS file contains sign lines (lines with a pos tag) and you don’t want them to be stripped, you can use this option.
# Valid options: bottom, top, and none
keep_ts=none

# Removes entries like "(wind blowing)" or "MAN 1:"
# Don’t expect perfect results. If you have a SDH subtitle, and the cues are very distracting, you might want to try this setting.
remove_sdh_entries=no

# Enable extended search for external subtitles
# Loads subtitles from subfolders with the same name as the video file. Useful for series.
# Do not enable this setting if you are using something similar.
expand_subtitle_search=no

# Keep italics during merging
detect_italics=yes

# Prevents you from seeing the same text 20 times on the screen.
remove_repeating_lines=no